name: Build and Zip Executable

on:
  release:
    types: [created]

  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: 'Tag name that the major tag will point to'
        required: true

env:
  TAG_NAME: ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }}

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Generate executable
      run: |
        poetry run build

    - name: Zip the executable
      run: |
        powershell Compress-Archive -Path dist\vpx_gamepad.exe -DestinationPath "vpx_gamepad_${{ env.TAG_NAME }}.zip"

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./vpx_gamepad_${{ env.TAG_NAME }}.zip
        asset_name: vpx_gamepad_${{ env.TAG_NAME }}.zip
        asset_content_type: application/zip
