name: Build and Zip Executable

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Set release version
      run: echo "RELEASE_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
    
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Generate executable
      run: |
        poetry run build

    - name: Zip the executable
      run: |
        powershell Compress-Archive -Path dist\vpx_gamepad.exe -DestinationPath "vpx_gamepad_${{ env.RELEASE_VERSION }}.zip"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: vpx_gamepad_${{ env.RELEASE_VERSION }}.zip
        path: vpx_gamepad_${{ env.RELEASE_VERSION }}.zip
